# Generated by Django 4.1.4 on 2023-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='amound',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
